# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-windows.yaml

on: [push]

env:
  SENZING_TOOLS_DATABASE_URL: 'sqlite3://na:na@nowhere/C:\Temp\sqlite\G2C.db'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        senzingapi-version: ["latest"]
        go: ["1.21"]
    name: Go ${{ matrix.go }} using Senzing API ${{ matrix.senzingapi-version }} on windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install Senzing API
        uses: Senzing/github-action-install-senzing-api@latest
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}
      - name: Add to "Path" environment variable
        run: echo "C:\Program Files\Senzing\g2\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Create empty database file
        run: |
          New-Item -Path "C:\Temp\sqlite\G2C.db" -ItemType File
      - name: Run go test
        run: go test -v -p 1 ./...
